time:
  num_of_sec_genrate_event_interval: 0.4
  
event:
  id_start_counting_at: 1
  id_jumps: 1
  message: "HELLO WORLD"
  timezone: "Asia/Jerusalem"

kafka_connection:
  attempt_to_connect_to_kafka_interval: 3